---
include:
  - '.gitlab/templates/rules.gitlab-ci.yml'
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/pip.gitlab-ci.yml'

python-sdk/flake8:
  variables:
    CI_SERVICE_REPO: utils/python-sdk
  extends:
    - .flake8
    - .mr-job

python-sdk/pytest:
  variables:
    CI_SERVICE_REPO: utils/python-sdk
  extends:
    - .pytest
    - .mr-job

python-sdk/pip-mr:
  variables:
    CI_SERVICE_REPO: utils/python-sdk
    VERSION_SUFFIX: '.dev215053772'
  extends:
    - .pip
    - .mr-job

python-sdk/pip-release:
  variables:
    CI_SERVICE_REPO: utils/python-sdk
  extends:
    - .pip
    - .release-job
