import os

DISPLAY_I2C_EXPANDER = os.environ.get('DISPLAY_I2C_EXPANDER', 'PCF8574')
DISPLAY_I2C_BUS = int(os.environ.get('DISPLAY_I2C_BUS'))
DISPLAY_I2C_ADDR = int(os.environ.get('DISPLAY_I2C_ADDR'), 16)
DISPLAY_BACKLIGHT_ENABLED = bool(os.environ.get('DISPLAY_BACKLIGHT_ENABLED', 'True'))
LCD_INFO_STATE_DURATION_SECONDS = int(os.environ.get('LCD_INFO_STATE_DURATION_SECONDS', 5))

METRICS_POLL_INTERVAL_SECONDS = int(os.environ.get('METRICS_POLL_INTERVAL_SECONDS', '1'))
METRICS_ENDPOINT_URL = os.environ.get('METRICS_ENDPOINT_URL')

FIFO = '/tmp/display_fifo'
