---
stages:
  - lint
  - test
  - build

include:
  - local: 'controller/src/button-controller/.gitlab-ci.yml'
  - local: 'controller/src/display-controller/.gitlab-ci.yml'
  - local: 'controller/src/led-controller/.gitlab-ci.yml'
