---
include:
  - '.gitlab/templates/rules.gitlab-ci.yml'
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker.gitlab-ci.yml'

serial-router/flake8:
  extends:
    - .flake8
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/serial-router

serial-router/pytest:
  extends:
    - .pytest
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/serial-router

serial-router/docker-build-mr:
  extends:
    - .docker
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/serial-router
    IMAGE_NAME: pipdu-serial-router

serial-router/docker-build-release:
  extends:
    - .docker
    - .release-job
  variables:
    CI_SERVICE_REPO: services/serial-router
    IMAGE_NAME: pipdu-serial-router

