---
include: 
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker-build.gitlab-ci.yml'

api-server/flake8:
  extends: .flake8
  variables:
    CI_SERVICE_REPO: services/api-server

api-server/pytest:
  extends: .pytest
  variables:
    CI_SERVICE_REPO: services/api-server

api-server/docker-build-mr:
  extends: .docker-build-mr
  variables:
    CI_SERVICE_REPO: services/api-server
    IMAGE_NAME: pipdu-api-server

api-server/docker-build-release:
  extends: .docker-build-release
  variables:
    CI_SERVICE_REPO: services/api-server
    IMAGE_NAME: pipdu-api-server
