---
include: 
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker-build.gitlab-ci.yml'

variables:
  CI_SERVICE_REPO: controller/src/button-controller
  IMAGE_NAME: pipdu-button-controller

button-controller/flake8:
  extends: .flake8

button-controller/pytest:
  extends: .pytest

button-controller/docker-build-mr:
  extends: .docker-build-mr

button-controller/docker-build-release:
  extends: .docker-build-release
