---
version: '2.2'

services:
  button-controller:
    image: antonmircea/pipdu-button-controller
    restart: unless-stopped
    environment:
      EXPANDER_I2C_BUS: 3
      EXPANDER_I2C_ADDR: 0x21,0x22
      BUTTON_PINS: 1,3,5,7,9,11,13,15,0,2,4,6,8,10,12
      BUTTON_POLL_INTERVAL_SECONDS: 0.5
      BUTTON_LONG_PRESS_DURATION_SECONDS: 3
      PIPDU_SERVER_ADDRESS: ""

  display-controller:
    image: antonmircea/pipdu-display-controller
    restart: unless-stopped
    environment:
      DISPLAY_I2C_BUS: 1
      DISPLAY_I2C_ADDR: 0x27
      DISPLAY_BACKLIGHT_ENABLED: True
      METRICS_POLL_INTERVAL_SECONDS: 0.5
      METRICS_ENDPOINT_URL: ""

  led-controller:
    image: antonmircea/pipdu-led-controller
    restart: unless-stopped
    environment:
      EXPANDER_I2C_BUS: 2
      EXPANDER_I2C_ADDR: 0x20,0x24
      LED_PINS: 1,3,5,7,9,11,13,15,0,2,4,6,8,10,12
      LED_UPDATE_INTERVAL_SECONDS: 0.5
      PIPDU_SERVER_ADDRESS: ""
