---
include:
  - '.gitlab/templates/rules.gitlab-ci.yml'
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker-build.gitlab-ci.yml'

led-controller/flake8:
  extends:
    - .flake8
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/led-controller

led-controller/pytest:
  extends:
    - .pytest
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/led-controller

led-controller/docker-build-mr:
  extends:
    - .docker
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/led-controller
    IMAGE_NAME: pipdu-led-controller

led-controller/docker-build-release:
  extends:
    - .docker
    - .release-job
  variables:
    CI_SERVICE_REPO: services/led-controller
    IMAGE_NAME: pipdu-led-controller
