---
include: 
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker-build.gitlab-ci.yml'

variables:
  CI_SERVICE_REPO: controller/src/display-controller
  IMAGE_NAME: pipdu-display-controller

display-controller/flake8:
  extends: .flake8

display-controller/pytest:
  extends: .pytest

display-controller/docker-build-mr:
  extends: .docker-build-mr

display-controller/docker-build-release:
  extends: .docker-build-release
