---
.flake8:
  stage: lint
  image: python:3.9
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - $CI_SERVICE_REPO/src/**/*

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip
      - venv/

  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

  script:
    - cd $CI_SERVICE_REPO
    - pip3 install -r requirements-dev.txt
    - flake8 --max-line-length=120 ./src/*
