---
include:
  - '.gitlab/templates/rules.gitlab-ci.yml'
  - '.gitlab/templates/lint.gitlab-ci.yml'
  - '.gitlab/templates/test.gitlab-ci.yml'
  - '.gitlab/templates/docker.gitlab-ci.yml'

metrics-server/flake8:
  extends:
    - .flake8
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/metrics-server

metrics-server/pytest:
  extends:
    - .pytest
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/metrics-server

metrics-server/docker-build-mr:
  extends:
    - .docker
    - .mr-job
  variables:
    CI_SERVICE_REPO: services/metrics-server
    IMAGE_NAME: pipdu-metrics-server

metrics-server/docker-build-release:
  extends:
    - .docker
    - .release-job
  variables:
    CI_SERVICE_REPO: services/metrics-server
    IMAGE_NAME: pipdu-metrics-server
